# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='es_animada',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
