# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_es_animada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=b'serie/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
