# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_auto_20160921_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
