# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20160922_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, upload_to=b'serie/')),
                ('sexo', models.CharField(choices=[(b'HOM', b'Hombre'), (b'MUJ', b'Mujer'), (b'OTR', b'Otro')], max_length=3)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Serie')),
            ],
        ),
    ]
