# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_personaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaje',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
